# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tk < Formula
  desc "Minimal task tracker CLI"
  homepage "https://github.com/nijaru/tk"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nijaru/tk/releases/download/v0.1.0/tk_darwin_amd64.tar.gz"
      sha256 "912ad34df3b3504637799613408efd95338eb50d670b45021bdbdc9eb7b20a85"

      define_method(:install) do
        bin.install "tk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nijaru/tk/releases/download/v0.1.0/tk_darwin_arm64.tar.gz"
      sha256 "50887759abcd332bbe4b1d9c3646692bce6bc3faebcf51dcfa16604421af9e34"

      define_method(:install) do
        bin.install "tk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nijaru/tk/releases/download/v0.1.0/tk_linux_amd64.tar.gz"
      sha256 "36cb4222ea72b9688787afb50974e20d89cfa72d32a69a53b0093fffec5e2377"
      define_method(:install) do
        bin.install "tk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nijaru/tk/releases/download/v0.1.0/tk_linux_arm64.tar.gz"
      sha256 "387fd1d90a6626bbe15fd60801f98bf3174ecf35b79aac6748e1c6ee2f161385"
      define_method(:install) do
        bin.install "tk"
      end
    end
  end

  test do
    system "#{bin}/tk", "--version"
  end
end
