# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tk < Formula
  desc "Minimal task tracker CLI"
  homepage "https://github.com/nijaru/tk"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nijaru/tk/releases/download/v0.1.2/tk_darwin_amd64.tar.gz"
      sha256 "fdf2f12f46ed23b7b9d80f97a65cf023a0cfdcc87e5369d5d5c5b424ac99d25a"

      define_method(:install) do
        bin.install "tk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nijaru/tk/releases/download/v0.1.2/tk_darwin_arm64.tar.gz"
      sha256 "5c0a9e42715ad1be13e52ace720fc6f1c9f5989c8839f8e1bf5a39a5f20df10a"

      define_method(:install) do
        bin.install "tk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nijaru/tk/releases/download/v0.1.2/tk_linux_amd64.tar.gz"
      sha256 "829729f0202f5428e01ce731e0c759aacf57703ab383f7313399c1efb9256100"
      define_method(:install) do
        bin.install "tk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nijaru/tk/releases/download/v0.1.2/tk_linux_arm64.tar.gz"
      sha256 "cdf722ae668179c5ac7bbfbe4582a68c89895807dd4f04f78bce3ae4289c8b11"
      define_method(:install) do
        bin.install "tk"
      end
    end
  end

  test do
    system "#{bin}/tk", "--version"
  end
end
