# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tk < Formula
  desc "Minimal task tracker CLI"
  homepage "https://github.com/nijaru/tk"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nijaru/tk/releases/download/v0.1.1/tk_darwin_amd64.tar.gz"
      sha256 "0bb08f7113096d8e118cf86394dbe1654247d6b5e728e655d878dec392071521"

      define_method(:install) do
        bin.install "tk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nijaru/tk/releases/download/v0.1.1/tk_darwin_arm64.tar.gz"
      sha256 "92136c39fb5f6bf48fc90febb7096338b6774ad6003aa58ad0997fe4439bd464"

      define_method(:install) do
        bin.install "tk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nijaru/tk/releases/download/v0.1.1/tk_linux_amd64.tar.gz"
      sha256 "6db4a7e4a71de16603f1f550b8d083a9a14fccaf3e59181ce702bcba4284dc9a"
      define_method(:install) do
        bin.install "tk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nijaru/tk/releases/download/v0.1.1/tk_linux_arm64.tar.gz"
      sha256 "5833259bf3985ce44552d77137e373f4c3bc5b6bdfd9e1f8934e0b32ed400a61"
      define_method(:install) do
        bin.install "tk"
      end
    end
  end

  test do
    system "#{bin}/tk", "--version"
  end
end
