# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tk < Formula
  desc "Minimal task tracker CLI"
  homepage "https://github.com/nijaru/tk"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nijaru/tk/releases/download/v0.1.2/tk_darwin_amd64.tar.gz"
      sha256 "3fd356ae3abf4b3103c608ba922862d5014aec66610edbc889b8dfede2dd0382"

      define_method(:install) do
        bin.install "tk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nijaru/tk/releases/download/v0.1.2/tk_darwin_arm64.tar.gz"
      sha256 "ecce11b099d1c3d914e435a9018dde36982d2ce0e63938a9c68d693c7d23c27b"

      define_method(:install) do
        bin.install "tk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nijaru/tk/releases/download/v0.1.2/tk_linux_amd64.tar.gz"
      sha256 "7009e31125dbf6ad5b343e3a3be10779db58890f977c3573dffb0ea69b4643b0"
      define_method(:install) do
        bin.install "tk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nijaru/tk/releases/download/v0.1.2/tk_linux_arm64.tar.gz"
      sha256 "185422315be34efdab3ef3ceaed87c92d95470e9310e2e25c7c28273a84a5a7f"
      define_method(:install) do
        bin.install "tk"
      end
    end
  end

  test do
    system "#{bin}/tk", "--version"
  end
end
