name: Update Formula

on:
  repository_dispatch:
    types: [release-published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to update to (e.g., 0.1.12)'
        required: true
        type: string

jobs:
  update-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tap repository
        uses: actions/checkout@v4

      - name: Set version
        id: version
        run: |
          if [ "${{ github.event_name }}" = "repository_dispatch" ]; then
            VERSION="${{ github.event.client_payload.version }}"
          else
            VERSION="${{ inputs.version }}"
          fi
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "Updating to version: ${VERSION}"

      - name: Download tarball and calculate SHA256
        id: tarball
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          URL="https://github.com/nijaru/kombrucha/archive/refs/tags/v${VERSION}.tar.gz"
          echo "Downloading ${URL}"
          SHA256=$(curl -sL "${URL}" | shasum -a 256 | cut -d' ' -f1)
          echo "sha256=${SHA256}" >> $GITHUB_OUTPUT
          echo "SHA256: ${SHA256}"

      - name: Update formula
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          SHA256="${{ steps.tarball.outputs.sha256 }}"

          # Update version and SHA256 in formula
          sed -i "s|archive/refs/tags/v[0-9.]*\.tar\.gz|archive/refs/tags/v${VERSION}.tar.gz|" Formula/bru.rb
          sed -i "s|sha256 \".*\"|sha256 \"${SHA256}\"|" Formula/bru.rb

          echo "Formula updated to v${VERSION}"
          cat Formula/bru.rb

      - name: Commit and push changes
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Formula/bru.rb
          git commit -m "chore: update formula to v${VERSION}"
          git push
